name: Build release

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'temurin'
  FAKETIME_VERSION: '0.9.10'

jobs:
  libfaketime:
    name: 'Build libfaketime'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Compile
        run: |
          curl -L -O https://github.com/wolfcw/libfaketime/archive/refs/tags/v${{ env.FAKETIME_VERSION }}.tar.gz
          tar -xvzf *.tar.gz
          cd libfaketime-${{ env.FAKETIME_VERSION }}
          PREFIX=libfaketime/ make install

      - name: 'Upload library'
        uses: actions/upload-artifact@v3
        with:
          name: libfaketime
          path: |
            libfaketime

  nativeImage:
    name: 'Build native image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          java-version: ${{ env.JAVA_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Cache Maven'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 'Maven'
        run: mvn -B --file pom.xml clean package -Pnative

      - name: 'Move'
        run: mv target/faketime-operator-1.0.0-runner target/faketime-operator-runner

      - name: 'Upload binary'
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: |
            target/faketime-operator-runner

  docker:
    name: 'Build native image'
    runs-on: ubuntu-latest
    needs: [ nativeImage ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
